In [1]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\pc\anaconda3\lib\site-packages (2.4.1)
Requirement already satisfied: tensorflow-estimator<2.5.0,>=2.4.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: termcolor~=1.1.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: protobuf>=3.9.2 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (3.15.8)
Requirement already satisfied: grpcio~=1.32.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (1.32.0)
Requirement already satisfied: typing-extensions~=3.7.4 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (3.7.4.2)
Requirement already satisfied: wheel~=0.35 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (0.36.2)
Requirement already satisfied: keras-preprocessing~=1.1.2 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (1.1.2)
Requirement already satisfied: opt-einsum~=3.3.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: google-pasta~=0.2 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: numpy~=1.19.2 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (1.19.4)
Requirement already satisfied: six~=1.15.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (1.15.0)
Requirement already satisfied: tensorboard~=2.4 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse~=1.6.3 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: gast==0.3.3 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (0.3.3)
Requirement already satisfied: wrapt~=1.12.1 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (1.12.1)
Requirement already satisfied: absl-py~=0.10 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (0.12.0)
Requirement already satisfied: flatbuffers~=1.12.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (1.12)
Requirement already satisfied: h5py~=2.10.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\users\pc\anaconda3\lib\site-packages (from tensorboard~=2.4->tensorflow) (1.30.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\pc\anaconda3\lib\site-packages (from tensorboard~=2.4->tensorflow) (0.4.4)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\pc\anaconda3\lib\site-packages (from tensorboard~=2.4->tensorflow) (1.0.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorboard~=2.4->tensorflow) (2.24.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\pc\anaconda3\lib\site-packages (from tensorboard~=2.4->tensorflow) (3.3.4)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorboard~=2.4->tensorflow) (0.6.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorboard~=2.4->tensorflow) (1.8.0)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\pc\anaconda3\lib\site-packages (from tensorboard~=2.4->tensorflow) (49.2.0.post20200714)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\pc\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in c:\users\pc\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\pc\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow) (4.2.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\pc\anaconda3\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow) (1.3.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow) (3.0.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\pc\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\pc\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow) (3.1.0)

In [2]:
!pip install keras

Requirement already satisfied: keras in c:\users\pc\anaconda3\lib\site-packages (2.4.3)
Requirement already satisfied: pyyaml in c:\users\pc\anaconda3\lib\site-packages (from keras) (5.3.1)
Requirement already satisfied: numpy>=1.9.1 in c:\users\pc\anaconda3\lib\site-packages (from keras) (1.19.4)
Requirement already satisfied: h5py in c:\users\pc\anaconda3\lib\site-packages (from keras) (2.10.0)
Requirement already satisfied: scipy>=0.14 in c:\users\pc\anaconda3\lib\site-packages (from keras) (1.5.0)
Requirement already satisfied: six in c:\users\pc\anaconda3\lib\site-packages (from h5py->keras) (1.15.0)

In [3]:
import numpy as np
import pandas as pd

In [4]:
# importing neccessary model for implementation of ANN
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [5]:
gas = pd.read_csv('I:\\Assigment - Data Science\\Neural Network\\gas_turbines.csv',delimiter =',')

In [6]:
gas

,AT,AP,AH,AFDP,GTEP,TIT,TAT,TEY,CDP,CO,NOX
0,6.8594,1007.9,96.799,3.5000,19.663,1059.2,550.00,114.70,10.605,3.1547,82.722
1,6.7850,1008.4,97.118,3.4998,19.728,1059.3,550.00,114.72,10.598,3.2363,82.776
2,6.8977,1008.8,95.939,3.4824,19.779,1059.4,549.87,114.71,10.601,3.2012,82.468
3,7.0569,1009.2,95.249,3.4805,19.792,1059.6,549.99,114.72,10.606,3.1923,82.670
4,7.3978,1009.7,95.150,3.4976,19.765,1059.7,549.98,114.72,10.612,3.2484,82.311
...,...,...,...,...,...,...,...,...,...,...,...
15034,9.0301,1005.6,98.460,3.5421,19.164,1049.7,546.21,111.61,10.400,4.5186,79.559
15035,7.8879,1005.9,99.093,3.5059,19.414,1046.3,543.22,111.78,10.433,4.8470,79.917
15036,7.2647,1006.3,99.496,3.4770,19.530,1037.7,537.32,110.19,10.483,7.9632,90.912
15037,7.0060,1006.8,99.008,3.4486,19.377,1043.2,541.24,110.74,10.533,6.2494,93.227
15038,6.9279,1007.2,97.533,3.4275,19.306,1049.9,545.85,111.58,10.583,4.9816,92.498

In [7]:
gas = gas[['AT','AP','AH','AFDP','GTEP','TIT','TAT','CDP','CO','NOX','TEY']]

In [8]:
gas

,AT,AP,AH,AFDP,GTEP,TIT,TAT,CDP,CO,NOX,TEY
0,6.8594,1007.9,96.799,3.5000,19.663,1059.2,550.00,10.605,3.1547,82.722,114.70
1,6.7850,1008.4,97.118,3.4998,19.728,1059.3,550.00,10.598,3.2363,82.776,114.72
2,6.8977,1008.8,95.939,3.4824,19.779,1059.4,549.87,10.601,3.2012,82.468,114.71
3,7.0569,1009.2,95.249,3.4805,19.792,1059.6,549.99,10.606,3.1923,82.670,114.72
4,7.3978,1009.7,95.150,3.4976,19.765,1059.7,549.98,10.612,3.2484,82.311,114.72
...,...,...,...,...,...,...,...,...,...,...,...
15034,9.0301,1005.6,98.460,3.5421,19.164,1049.7,546.21,10.400,4.5186,79.559,111.61
15035,7.8879,1005.9,99.093,3.5059,19.414,1046.3,543.22,10.433,4.8470,79.917,111.78
15036,7.2647,1006.3,99.496,3.4770,19.530,1037.7,537.32,10.483,7.9632,90.912,110.19
15037,7.0060,1006.8,99.008,3.4486,19.377,1043.2,541.24,10.533,6.2494,93.227,110.74
15038,6.9279,1007.2,97.533,3.4275,19.306,1049.9,545.85,10.583,4.9816,92.498,111.58

In [9]:
label_encoder = preprocessing.LabelEncoder()
gas['AT'] = label_encoder.fit_transform(gas['AT'])

In [10]:
label_encoder = preprocessing.LabelEncoder()
gas['AP'] = label_encoder.fit_transform(gas['AP'])

In [11]:
label_encoder = preprocessing.LabelEncoder()
gas['AH'] = label_encoder.fit_transform(gas['AH'])

In [12]:
label_encoder = preprocessing.LabelEncoder()
gas['AFDP'] = label_encoder.fit_transform(gas['AFDP'])

In [13]:
label_encoder = preprocessing.LabelEncoder()
gas['GTEP'] = label_encoder.fit_transform(gas['GTEP'])

In [14]:
label_encoder = preprocessing.LabelEncoder()
gas['TIT'] = label_encoder.fit_transform(gas['TIT'])

In [15]:
label_encoder = preprocessing.LabelEncoder()
gas['TAT'] = label_encoder.fit_transform(gas['TAT'])

In [16]:
label_encoder = preprocessing.LabelEncoder()
gas['CDP'] = label_encoder.fit_transform(gas['CDP'])

In [17]:
label_encoder = preprocessing.LabelEncoder()
gas['TEY'] = label_encoder.fit_transform(gas['TEY'])

In [18]:
label_encoder = preprocessing.LabelEncoder()
gas['CO'] = label_encoder.fit_transform(gas['CO'])

In [19]:
label_encoder = preprocessing.LabelEncoder()
gas['NOX'] = label_encoder.fit_transform(gas['NOX'])

In [20]:
gas.isnull().sum().sum()

0

In [21]:
gas

         AT   AP     AH  AFDP  GTEP  TIT   TAT  CDP     CO    NOX  TEY
0      1230  292  12092  2208   787  292  2285  461  10695  10885  707
1      1199  297  12149  2207   842  293  2285  454  10775  10892  709
2      1251  301  11882  2148   883  294  2272  457  10746  10835  708
3      1334  305  11699  2138   892  296  2284  462  10738  10875  709
4      1505  310  11676  2197   871  297  2283  468  10782  10774  709
...     ...  ...    ...   ...   ...  ...   ...  ...    ...    ...  ...
15034  2278  269  12369  2376   382  197  1964  256  11809  10229  491
15035  1732  272  12467  2230   577  163  1742  289  12015  10317  508
15036  1433  276  12533  2121   675   83  1247  339  12818  11571  352
15037  1302  281  12449  2009   545  135  1583  389  12579  11636  406
15038  1266  285  12227  1953   485  199  1939  439  12087  11620  488

[15039 rows x 11 columns]

In [22]:
X = gas.iloc[:,0:10]
Y = gas.iloc[:,-1]

In [23]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3)

## First Model
No. of Input features = 10
No of Hidden layer = 1
No. of hidden neuron = 12
No. of dimension of output = 1

In [24]:
column_names = list(gas.columns)
predictors = column_names[0:10]
target = column_names[-1]
predictors

['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'CDP', 'CO', 'NOX']

In [25]:
def prep_model(hidden_dim):
    model = Sequential()
    for i in range(1,len(hidden_dim)-1):
        if (i==1):
            model.add(Dense(hidden_dim[i],input_dim=hidden_dim[0],kernel_initializer="normal",activation="relu"))
        else:
            model.add(Dense(hidden_dim[i],activation="relu"))
    # for the output layer we are not adding any activation function as 
    # the target variable is continuous variable 
    model.add(Dense(hidden_dim[-1]))
    # loss ---> loss function is means squared error to compare the output and estimated output
    # optimizer ---> adam
    # metrics ----> mean squared error - error for each epoch on entire data set 
    model.compile(loss="mean_squared_error",optimizer="adam",metrics = ["mse"])
    return (model)

In [26]:
first_model = prep_model([10,100,1])
first_model.fit((gas.iloc[:,0:10]),(gas.iloc[:,-1]),epochs=20)

Epoch 1/20
470/470 [==============================] - 2s 1ms/step - loss: 798452.6119 - mse: 798452.6119
Epoch 2/20
470/470 [==============================] - 0s 1ms/step - loss: 8635.0329 - mse: 8635.0329
Epoch 3/20
470/470 [==============================] - 0s 1ms/step - loss: 7356.7392 - mse: 7356.7392
Epoch 4/20
470/470 [==============================] - 0s 1ms/step - loss: 5915.6563 - mse: 5915.6563
Epoch 5/20
470/470 [==============================] - 0s 1ms/step - loss: 5692.7688 - mse: 5692.7688
Epoch 6/20
470/470 [==============================] - 0s 994us/step - loss: 5375.3146 - mse: 5375.3146
Epoch 7/20
470/470 [==============================] - 0s 936us/step - loss: 4970.4090 - mse: 4970.4090
Epoch 8/20
470/470 [==============================] - 0s 994us/step - loss: 4859.2329 - mse: 4859.2329
Epoch 9/20
470/470 [==============================] - 0s 921us/step - loss: 5002.1140 - mse: 5002.1140
Epoch 10/20
470/470 [==============================] - 0s 945us/step - loss: 4902.5996 - mse: 4902.5996
Epoch 11/20
470/470 [==============================] - 0s 994us/step - loss: 5086.9674 - mse: 5086.9674
Epoch 12/20
470/470 [==============================] - 0s 983us/step - loss: 4727.1243 - mse: 4727.1243
Epoch 13/20
470/470 [==============================] - 0s 932us/step - loss: 4606.5753 - mse: 4606.5753
Epoch 14/20
470/470 [==============================] - 0s 914us/step - loss: 4547.5120 - mse: 4547.5120
Epoch 15/20
470/470 [==============================] - 0s 909us/step - loss: 4302.1938 - mse: 4302.1938
Epoch 16/20
470/470 [==============================] - 0s 904us/step - loss: 4458.2431 - mse: 4458.2431
Epoch 17/20
470/470 [==============================] - 0s 944us/step - loss: 3945.6130 - mse: 3945.6130
Epoch 18/20
470/470 [==============================] - 0s 909us/step - loss: 4037.2381 - mse: 4037.2381
Epoch 19/20
470/470 [==============================] - 0s 913us/step - loss: 4610.7072 - mse: 4610.7072
Epoch 20/20
470/470 [==============================] - 0s 919us/step - loss: 4186.0372 - mse: 4186.0372

In [27]:
first_model = prep_model([10,100,1])

In [28]:
pred_train = first_model.predict(np.array(train[predictors]))
pred_train = pd.Series([i[0] for i in pred_train])
rmse_value = np.sqrt(np.mean((pred_train-train[target])**2))
rmse_value

NameError: name 'train' is not defined